#!/bin/bash
# =============================================================================
# install.sh — options_trader v1.0 Web Installer
# Run on a fresh EC2 via:
#   curl -fsSL https://raw.githubusercontent.com/TX-9AI/options_trader_v1/main/install.sh -o install.sh && bash install.sh
# =============================================================================

set -e
export DEBIAN_FRONTEND=noninteractive

REPO="https://github.com/TX-9AI/options_trader_v1.git"
INSTALL_DIR="$HOME/options-trader"
SERVICE_NAME="optionsbot"
VENV="$INSTALL_DIR/venv"

exec < /dev/tty

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║      options_trader v1.0  |  Vertigo Capital        ║"
echo "║      QQQ 0DTE  |  TastyTrade  |  Web Installer     ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
echo "  Have ready:"
echo "    - TastyTrade username & password"
echo "    - Telegram bot token & chat ID"
echo ""
echo "Press ENTER to continue or Ctrl+C to cancel."
read -r _

# ── 1. System packages ────────────────────────────────────────────────────────
echo ""
echo "[ 1/7 ] Installing system packages..."
sudo DEBIAN_FRONTEND=noninteractive apt-get update -qq
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
    python3 python3-pip python3-venv git sqlite3 curl bc
echo "  Done."

# ── 2. Clone repo ─────────────────────────────────────────────────────────────
echo ""
echo "[ 2/7 ] Cloning repository..."
if [ -d "$INSTALL_DIR" ]; then
    echo "  Directory exists — pulling latest..."
    cd "$INSTALL_DIR" && git pull
else
    git clone "$REPO" "$INSTALL_DIR"
fi
echo "  Done."

# ── 3. Credentials ────────────────────────────────────────────────────────────
echo ""
echo "[ 3/7 ] Credentials"
echo ""
printf "  TastyTrade Username: "; read -r TT_USERNAME
printf "  TastyTrade Password: "; read -r TT_PASSWORD
echo ""
printf "  Telegram Bot Token: "; read -r TELEGRAM_TOKEN
printf "  Telegram Chat ID: "; read -r TELEGRAM_CHAT_ID

# ── 4. Trading mode ───────────────────────────────────────────────────────────
echo ""
echo "[ 4/7 ] Trading mode"
echo ""
printf "  Paper trading? [Y/n, default=Y]: "; read -r PAPER_INPUT
PAPER_INPUT="${PAPER_INPUT:-Y}"
if [[ "$PAPER_INPUT" =~ ^[Nn] ]]; then
    PAPER_TRADING="False"
    echo "  ⚠️  LIVE TRADING — real orders will be sent to TastyTrade"
else
    PAPER_TRADING="True"
    echo "  PAPER mode — no real orders placed"
fi

echo ""
echo "  Risk per trade: \$200 (Grade A=1.5x, Grade B=1.0x)"
echo "  Instrument: QQQ 0DTE"
echo "  Strategies: ORB, Sweep Reversal, Butterfly (COMPRESSION only)"

# ── 5. Python venv ────────────────────────────────────────────────────────────
echo ""
echo "[ 5/7 ] Creating Python environment..."
python3 -m venv "$VENV"
source "$VENV/bin/activate"
pip install --upgrade pip -q
pip install -r "$INSTALL_DIR/requirements.txt" -q
pip install yfinance requests -q
echo "  Done."

# ── 6. Credentials file ───────────────────────────────────────────────────────
echo ""
echo "[ 6/7 ] Writing credentials..."
cat > "$INSTALL_DIR/credentials.py" << CREDEOF
"""
credentials.py — Generated by install.sh on $(date)
DO NOT commit this file to GitHub.
"""

TT_USERNAME = "$TT_USERNAME"
TT_PASSWORD = "$TT_PASSWORD"

TWILIO_ACCOUNT_SID  = ""
TWILIO_AUTH_TOKEN   = ""
TWILIO_FROM_NUMBER  = ""
ALERT_TO_PHONE      = ""
CREDEOF

chmod 600 "$INSTALL_DIR/credentials.py"
chmod +x "$INSTALL_DIR/setup_ec2.sh" 2>/dev/null || true
echo "  Done."

# ── 7. Systemd service ────────────────────────────────────────────────────────
echo ""
echo "[ 7/7 ] Creating systemd service..."

sudo tee /etc/systemd/system/${SERVICE_NAME}.service > /dev/null << SVCEOF
[Unit]
Description=options_trader v1.0 — QQQ 0DTE | Vertigo Capital
After=network.target

[Service]
Type=simple
User=ubuntu
WorkingDirectory=$INSTALL_DIR
Environment="PAPER_TRADING=$PAPER_TRADING"
Environment="TELEGRAM_TOKEN=$TELEGRAM_TOKEN"
Environment="TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID"
ExecStartPre=/bin/bash -c 'touch $INSTALL_DIR/bot.log $INSTALL_DIR/trades.db; chown ubuntu:ubuntu $INSTALL_DIR/bot.log $INSTALL_DIR/trades.db'
ExecStart=$VENV/bin/python main.py --service
Restart=on-failure
RestartSec=30
StandardOutput=journal
StandardError=journal
Environment=PYTHONUNBUFFERED=1

[Install]
WantedBy=multi-user.target
SVCEOF

sudo systemctl daemon-reload
sudo systemctl enable $SERVICE_NAME

# Bash profile
grep -q "options-trader/venv" ~/.bashrc || echo "source $VENV/bin/activate" >> ~/.bashrc
grep -q "cd ~/options-trader" ~/.bashrc  || echo "cd $INSTALL_DIR" >> ~/.bashrc

# Start bot
touch "$INSTALL_DIR/bot.log" "$INSTALL_DIR/trades.db"
chown ubuntu:ubuntu "$INSTALL_DIR/bot.log" "$INSTALL_DIR/trades.db" "$INSTALL_DIR/credentials.py"

sudo systemctl start $SERVICE_NAME
sleep 8

STATUS=$(systemctl is-active $SERVICE_NAME)
if [ "$STATUS" = "active" ]; then
    echo ""
    echo "╔══════════════════════════════════════════════════════╗"
    echo "║              ✅  Install Complete!                  ║"
    echo "╚══════════════════════════════════════════════════════╝"
    echo ""
    echo "  Instrument: QQQ 0DTE (TastyTrade)"
    echo "  Mode:       $([ "$PAPER_TRADING" = "True" ] && echo "PAPER" || echo "LIVE ⚠️")"
    echo "  Telegram:   chat $TELEGRAM_CHAT_ID"
    echo "  Service:    $SERVICE_NAME"
    echo ""
    echo "  Commands:"
    echo "    python status.py                    — live status"
    echo "    python query.py                     — performance dashboard"
    echo "    journalctl -u $SERVICE_NAME -f      — live logs"
    echo "    journalctl -u $SERVICE_NAME -n 30 --no-pager | grep -v 'tastytrade\|FEED_DATA\|received'"
    echo ""
    source "$VENV/bin/activate" && python "$INSTALL_DIR/status.py"
else
    echo ""
    echo "  ⚠️  Service did not start."
    echo "  Check: journalctl -u $SERVICE_NAME -n 30 --no-pager"
fi
